#!/usr/bin/env python3
"""
Auto-generate the "Trackable Quantities" table in README.md from the
quantities registered in torch_tracker/quantities.py.

The table lists every quantity registered in ``QUANTITY_REGISTRY`` (in the
order it is registered) alongside the docstring of the function that computes
it. It is written into README.md between the marker comments::

    <!-- BEGIN QUANTITIES TABLE ... -->
    <!-- END QUANTITIES TABLE -->

Usage
-----
    python tools/generate_quantities_table.py          # rewrite the table in README.md
    python tools/generate_quantities_table.py --check   # exit 1 if README is out of date

This uses only the standard library (``ast``) and does NOT import
torch_tracker, so it needs no scientific dependencies (yt, h5py, ...).
"""
from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
QUANTITIES_PY = REPO_ROOT / "torch_tracker" / "quantities.py"
README = REPO_ROOT / "README.md"

BEGIN = ("<!-- BEGIN QUANTITIES TABLE "
         "(auto-generated by tools/generate_quantities_table.py; do not edit by hand) -->")
END = "<!-- END QUANTITIES TABLE -->"


def collect_registered_quantities(source: str):
    """Return a list of (quantity_name, docstring) in registration order."""
    tree = ast.parse(source)

    # Map function name -> cleaned docstring.
    docstrings = {
        node.name: (ast.get_docstring(node, clean=True) or "")
        for node in ast.walk(tree)
        if isinstance(node, ast.FunctionDef)
    }

    quantities = []
    for node in tree.body:
        # Looking for: QUANTITY_REGISTRY["name"] = func_name
        if not (isinstance(node, ast.Assign) and len(node.targets) == 1):
            continue
        target = node.targets[0]
        if not (isinstance(target, ast.Subscript)
                and isinstance(target.value, ast.Name)
                and target.value.id == "QUANTITY_REGISTRY"):
            continue
        key = target.slice
        if not (isinstance(key, ast.Constant) and isinstance(key.value, str)):
            continue
        if not isinstance(node.value, ast.Name):
            continue
        qname = key.value
        docstring = docstrings.get(node.value.id, "")
        quantities.append((qname, docstring))

    return quantities


def build_table(quantities) -> str:
    """Render the quantities as a GitHub-flavored markdown table."""
    rows = ["| Quantity | Description |", "| --- | --- |"]
    for qname, docstring in quantities:
        # Collapse all whitespace (incl. newlines) to single spaces so the
        # docstring fits in one table cell, and escape pipes so they don't
        # break the table (e.g. virial ratios documented as |sum(K)/sum(U)|).
        description = " ".join(docstring.split()).replace("|", "\\|")
        if not description:
            description = "—"
        rows.append(f"| `{qname}` | {description} |")
    return "\n".join(rows)


def render_readme(readme_text: str, table: str) -> str:
    """Return README text with the region between the markers replaced."""
    try:
        pre, rest = readme_text.split(BEGIN, 1)
        _, post = rest.split(END, 1)
    except ValueError:
        raise SystemExit(
            f"Could not find the table markers in {README}. Expected:\n"
            f"  {BEGIN}\n  {END}"
        )
    return f"{pre}{BEGIN}\n{table}\n{END}{post}"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Do not write; exit 1 if README.md is out of date.",
    )
    args = parser.parse_args(argv)

    quantities = collect_registered_quantities(QUANTITIES_PY.read_text())
    table = build_table(quantities)
    current = README.read_text()
    updated = render_readme(current, table)

    if args.check:
        if current != updated:
            print(
                "README.md quantities table is out of date. "
                "Run: python tools/generate_quantities_table.py",
                file=sys.stderr,
            )
            return 1
        print(f"README.md quantities table is up to date ({len(quantities)} quantities).")
        return 0

    if current != updated:
        README.write_text(updated)
        print(f"Updated README.md quantities table ({len(quantities)} quantities).")
    else:
        print(f"README.md quantities table already up to date ({len(quantities)} quantities).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
